### ISSUE TITLE
Impose brows

### ISSUE THREAD

**Issue by anoire73** [wuhuikai/FaceSwap#1]
Hello!
It's not issue, just small request.
Whether it is possible to make to impose brows?

For example
https://matthewearl.github.io/2015/07/28/switching-eds-with-python/

Thanks!

**Comment by wuhuikai** [comment]
It mainly depends on the point detection algorithms. The algorithm I used can't handle well with the eyebrows. I think you can try to replace it with a CNN-based algorithm like [this one](https://github.com/zeusees/HyperLandmark).

**Comment by anoire73** [comment]
Thanks, but i use hack, and set eyebrow coordinates bigger for masks. It turns out what you need, eyebrows are captured.  10.09.2018, 09:54, "Wu Huikai" <notifications@github.com>:It mainly depends on the point detection algorithms. The algorithm I used can't handle well with the eyebrows. I think you can try to replace it with a CNN-based algorithm like this one.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Clark-zhang** [comment]
> Thanks, but i use hack, and set eyebrow coordinates bigger for masks. It turns out what you need, eyebrows are captured.  10.09.2018, 09:54, "Wu Huikai" <notifications@github.com>:It mainly depends on the point detection algorithms. The algorithm I used can't handle well with the eyebrows. I think you can try to replace it with a CNN-based algorithm like this one.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

Hi, @anoire73 
Could you tell me which line in the code you modified to be able to swap eyebrows too? Thanks :)

**Comment by anoire73** [comment]
Hello! I changed the coordinates of the face mask points.For one face def select_face(im, r=20):    faces = face_detection(im)     if len(faces) == 0:        print('Detect 0 Face !!!')        exit(-1)     bbox = faces[0]            points = np.asarray(face_points_detection(im, bbox))        points[17] = points[17] - np.asarray([[0, 40]])    points[18] = points[18] - np.asarray([[0, 40]])            points[19] = points[19] - np.asarray([[0, 40]])    points[20] = points[20] - np.asarray([[0, 40]])            points[21] = points[21] - np.asarray([[0, 40]])    points[22] = points[22] - np.asarray([[0, 40]])                points[23] = points[23] - np.asarray([[0, 40]])    points[24] = points[24] - np.asarray([[0, 40]])            points[25] = points[25] - np.asarray([[0, 40]])    points[26] = points[26] - np.asarray([[0, 40]])            points[27] = points[27] - np.asarray([[0, 40]])                    im_w, im_h = im.shape[:2]    left, top = np.min(points, 0)    right, bottom = np.max(points, 0)        x, y = max(0, left-r), max(0, top-r)    w, h = min(right+r, im_h)-x, min(bottom+r, im_w)-y     return points - np.asarray([[x, y]]), (x, y, w, h), im[y:y+h, x:x+w]  17.02.2019, 10:18, "Clark Zhang" <notifications@github.com>:Thanks, but i use hack, and set eyebrow coordinates bigger for masks. It turns out what you need, eyebrows are captured.  10.09.2018, 09:54, "Wu Huikai" notifications@github.com:It mainly depends on the point detection algorithms. The algorithm I used can't handle well with the eyebrows. I think you can try to replace it with a CNN-based algorithm like this one.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.Hi, @anoire73Could you tell me which line in the code you modified to be able to swap eyebrows too? Thanks :)—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Clark-zhang** [comment]
> points = np.asarray(face_points_detection(im, bbox))        points[17] = points[17] - np.asarray([[0, 40]])    points[18] = points[18] - np.asarray([[0, 40]])            points[19] = points[19] - np.asarray([[0, 40]])    points[20] = points[20] - np.asarray([[0, 40]])            points[21] = points[21] - np.asarray([[0, 40]])    points[22] = points[22] - np.asarray([[0, 40]])                points[23] = points[23] - np.asarray([[0, 40]])    points[24] = points[24] - np.asarray([[0, 40]])            points[25] = points[25] - np.asarray([[0, 40]])    points[26] = points[26] - np.asarray([[0, 40]])            points[27] = points[27] - np.asarray([[0, 40]])                    im_w, im_h = im.shape[:2]    left, top = np.min(points, 0)    right, bottom = np.max(points, 0)        x, y = max(0, left-r), max(0, top-r)    w, h = min(right+r, im_h)-x, min(bottom+r, im_w)-y     return points - np.asarray([[x, y]]), (x, y, w, h), im[y:y+h, x:x+w]


OK, thank you so much. Cheers 👍
