### ISSUE TITLE
Is it possible to swap multiple faces?

### ISSUE THREAD

**Issue by lightyrs** [wuhuikai/FaceSwap#14]
I am curious if there's a way for me to provide multiple source files and then have them be applied to faces in the dest image. The order doesn't really matter.

**Comment by wuhuikai** [comment]
It can be achieved by writing a loop yourself in this [file](https://github.com/wuhuikai/FaceSwap/blob/2c3644000227678c3506015c869336afc3876b71/main.py#L76).
