### ISSUE TITLE
Incorrect color using --warp_2d option

### ISSUE THREAD

**Issue by RyanBram** [wuhuikai/FaceSwap#16]
Hi, Developer.

Thank you for this great app.
I tried your app and work nicely.

When I was trying your app, sometimes `--warp_2d`  will give better result than without it.
The only issue that I found is `--wrap_2d` uses "face" color tone instead of using "target" color tone which resulting inconsistent result color.

Is it possible for `--wrap_2d` to also adjust the "face" color tone to follow "target" color tone?

Thanks

**Comment by wuhuikai** [comment]
1. Have you turned on `--correct_color`?
2. Can you provide the results with `--correct_color` on and off?

**Comment by RyanBram** [comment]
Hi.
Thank you for your reply.

I upload my sample picture and the results.
Both with `--correct_color` or without it has strange skin tone compared with only `--correct_color`
[sample.zip](https://github.com/wuhuikai/FaceSwap/files/3751037/sample.zip)

Thanks.

**Comment by wuhuikai** [comment]
The color of `--correct_color --warp2d` is consistent with that of `--correct_color`. I don't have any idea to improve it :(

**Comment by RyanBram** [comment]
Hi.
Please let me to give you a comparison to show if `--correct_color --warp2d` commands have noticeable color tone border especially in forehead that looks like straight line. The swapped face also looks darker compared to `--correct_color` only.
[sample.zip](https://github.com/wuhuikai/FaceSwap/files/3756949/sample.zip)


Thanks.

**Comment by wuhuikai** [comment]
I see, but I can't figure out the reason at present. I'll work on this problem in December.

**Comment by wuhuikai** [comment]
@RyanBram Now, both `warp_2d` and `warp_3d` can adjust the `src` color tone to follow the `dst` color tone.

**Comment by ghost** [comment]
I AM NOT AN EXPERT NOR AN AMAETUER BUT I WOUL LIKE SOMEONE TO HELP ME INITIALISE AND RUN THIS
