### ISSUE TITLE
I think this code is wrong. How about?

### ISSUE THREAD

**Issue by bii755** [wuhuikai/FaceSwap#17]
main.py, In select_face(), 47 line
**`im_w, im_h = im.shape[:2]`**
I think this must be wrong.
**`im_h , im_w = im.shape[:2]`**

In 52 line, So, It would change from 
**`w, h = min(right+r, im_h)-x, min(bottom+r, im_w)-y`**
to
**`w, h = min(right+r, im_w)-x, min(bottom+r, im_h)-y`**.

What do you think about that??

**Comment by wuhuikai** [comment]
I think it's just a name error, thus there's no effect on the running of the code.
