### ISSUE TITLE
do not understand function `correct_colours`

### ISSUE THREAD

**Issue by IamMegatron2025** [wuhuikai/FaceSwap#21]
Hello, I still can not understand the functionality of `correct_colours` function in [here](https://github.com/wuhuikai/FaceSwap/blob/master/face_swap.py#L145) .  Can you  explain it ?

Thanks.
Looking forward to your reply.

**Comment by wuhuikai** [comment]
It forces the average color of `result` to be close to the average color of `im2`.

**Comment by IamMegatron2025** [comment]
@wuhuikai  thanks for your reply. So the if `COLOUR_CORRECT_BLUR_FRAC` is smaller than 0.5, then the average color of result will be close to the average color of im1?

**Comment by wuhuikai** [comment]
Nope, `COLOUR_CORRECT_BLUR_FRAC` controls the window size for averaging the color.

**Comment by IamMegatron2025** [comment]
@wuhuikai  Thanks. So what should I do if I want to forces the average color of result to be close to the average color of im1?

**Comment by wuhuikai** [comment]
Then you should call this function with `im2` and `im1`.

**Comment by IamMegatron2025** [comment]
@wuhuikai Thanks for your reply. I am stupid. But I find that function `correct_colours(im1, im2, landmarks1)` forces the average color of result to be close to the average color of im1 rather than im2.

**Comment by wuhuikai** [comment]
My mistake :( You're right~

**Comment by IamMegatron2025** [comment]
@wuhuikai  thank you very much~~

About function `correct_colours`, we meet an another problem:
After I use `correct_colours(im1, im2, landmarks)`, there is a little white part on the edge of result face. How to fix this? Can you give some advises?


[im1.png](https://user-images.githubusercontent.com/13058184/79859400-8a671080-8403-11ea-9bdf-3460d0e3ba98.png) 
[im2.png](https://user-images.githubusercontent.com/13058184/79859406-90f58800-8403-11ea-9ff8-ba1d0f668a79.png)
[result.png](https://user-images.githubusercontent.com/13058184/79859421-9652d280-8403-11ea-944e-b4d3265fa83c.png)

Besides, `landmarks` is the face keypoints of `im1`.

**Comment by wuhuikai** [comment]
You can try to increase `COLOUR_CORRECT_BLUR_FRAC` or first align im1 and im2.
