### ISSUE TITLE
two problems.

### ISSUE THREAD

**Issue by IamMegatron2025** [wuhuikai/FaceSwap#22]
1. I do not understand why we need to erode the mask for dst_points [here](https://github.com/wuhuikai/FaceSwap/blob/master/face_swap.py#L139) . 

2.Without other op , simplely using `seamlessClone` op for blending two face image like `cv2.seamlessClone(src_img, dst_img, src_mask, center, cv2.NORMAL_CLONE)`, I test 3 cases:

a) When I use  all white mask for `src_mask`, there will be some white bright parts on the some edges of result face. 
b) When I use the same-sized face white mask of src_img for `src_mask`, there will be some bigger white bright parts on the some edges of result face.
c) When I use the eroded face white mask of src_img for `src_mask`, there will be some black parts on the some edges of result face. 

I can not find the causes and can not fix it. Can you give some advises?

Thanks.
Looking forward to your reply.

**Comment by wuhuikai** [comment]
1. Smaller face brings better visual quality.
2. Do you have any visual result?

**Comment by IamMegatron2025** [comment]
@wuhuikai  Thanks for your reply.

Got 1. For q2:

This a simple demo code:
```
import cv2
import numpy as np

ori_img = cv2.imread("xxx/ori_img1.png")
img2 = cv2.imread("xxx/img2.png")

# Poisson Blending
h, w = img2.shape[:2]
center = (102 + int(w / 2), 120 + int(h / 2))
face_mask = 255 * np.ones(img2.shape, img2.dtype)  # Create an all white mask
result = cv2.seamlessClone(img2, ori_img, face_mask, center, cv2.NORMAL_CLONE)
```
After poisson Blending, I find that there is a little white part on the upper right corner of result face.

[ori_img.png](https://user-images.githubusercontent.com/13058184/79864413-036a6600-840c-11ea-9f57-8eb5acca803a.png)
[im2.png](https://user-images.githubusercontent.com/13058184/79864408-01a0a280-840c-11ea-8762-e57219de9e9a.png)
[result.png](https://user-images.githubusercontent.com/13058184/79864418-049b9300-840c-11ea-9b4c-bdbfd5ea7c39.png)

**Comment by wuhuikai** [comment]
That's the issue of Poisson Image Editing, please try another blending algos such as drag and drop.
