### ISSUE TITLE
Speed Up

### ISSUE THREAD

**Issue by daiisuke27** [wuhuikai/FaceSwap#24]
Hello and thank you for your great work !
I edited your code to get different result (replaced dlib detector to swap the eyebrows too...). My issue is that i want to use it on realtime videos, what do you think is the best solution to speed up ? is there a way to run it on GPU ? or there's another solution ?
Thank's again !

**Comment by wuhuikai** [comment]
I'm not familiar with acceleration. But one possible way is 1. replace face detection with face tracking; and 2. implement the python part with c++ or cython or cuda.
