### ISSUE TITLE
Issue: setup the project.

### ISSUE THREAD

**Issue by jsdude0220** [wuhuikai/FaceSwap#27]
I have one issue when setup the project in local.
I have attached the error screen.
![Screenshot_1](https://user-images.githubusercontent.com/58881761/97190365-967fc080-17e0-11eb-863e-4b6e89bcff07.png)
I hope you to help me this.
Thanks.

**Comment by wuhuikai** [comment]
Do you click the right face?

**Comment by Cocktails0921** [comment]
Thanks for your response.
Hmm... Click the right face ?
What is mean?

**Comment by jsdude0220** [comment]
Thanks for your response.
I have executed the following command.
`python main.py --src imgs/test6.jpg --dst imgs/test7.jpg --out results/output6_7.jpg --correct_color`
And test6.jpg and test7.jpg images are already existed in imgs folder.
But when executed above command, I have got error message like my issue screenshot.

**Comment by jsdude0220** [comment]
![image](https://user-images.githubusercontent.com/58881761/97308399-cb048280-189b-11eb-8a72-a478047f336e.png)
This is my imgs files screenshot.

**Comment by jsdude0220** [comment]
Hello, @wuhuikai 
I have one strange issue.
Yesterday it does not work correctly. I have got the error message.
But today I have executed and it works well.
Strange issue.
And I have one quick question.
I'd like to this face swap function to integrated with website.
So I want to integrated this function in backend.
Which framework do you prefer as the backend ?
Thanks in advance.

**Comment by wuhuikai** [comment]
I prefer Flask, and here is one of my demo: https://github.com/wuhuikai/DeepCV
