### ISSUE TITLE
Simple face swap

### ISSUE THREAD

**Issue by arianaa30** [wuhuikai/FaceSwap#29]
Very interesting and easy to use work!
I was wondering, is there any ways not to transform the reference face? I'm simply looking for a replacement of the original face with of course clean edges and colors. But no transformation in the original face.

Is there a way to do it within the code?

![image](https://user-images.githubusercontent.com/5509837/100320345-ad076c00-2f86-11eb-97c1-b4fcbaf33852.png)

**Comment by wuhuikai** [comment]
Nope，because the sizes of faces are different, this will cause several problems.

**Comment by arianaa30** [comment]
Well, resizing is fine. I was thinking about the morphing and changes in
the shape of the face itself.

**Comment by wuhuikai** [comment]
There's no easy way to do so with the current code.

**Comment by ashbeats** [comment]
Based on your original reference image, Face Swap may not be right. 

What you need is a pipeline of different models similar to this:

```
object extraction → **bg isolation → edge refinement** → coordinate transformation of the feature points → global pixel normalization (artifact removal)
```



> Very interesting and easy to use work!
> I was wondering, is there any ways not to transform the reference face? I'm simply looking for a replacement of the original face with of course clean edges and colors. But no transformation in the original face.
> 
> Is there a way to do it within the code?
> 
> ![image](https://user-images.githubusercontent.com/5509837/100320345-ad076c00-2f86-11eb-97c1-b4fcbaf33852.png)
