### ISSUE TITLE
Videos with multiple faces

### ISSUE THREAD

**Issue by arianaa30** [wuhuikai/FaceSwap#32]
I see there a support to choose a face in a photo. How can we add this support in a video?
Take the simplest- Assuming the order of faces won't change, take an index as input and replace that index. 
e.g. **-index 2** replaces the 2nd face (from left to right). Or something similar.

**Comment by wuhuikai** [comment]
Basically, it's the same as what does in the image-level face swapping algo.

**Comment by arianaa30** [comment]
Ok...i wish you could help with the implementation or add this feature 😌

**Comment by wuhuikai** [comment]
Currently, I do not have any time to work on this.
