### ISSUE TITLE
TypeError: Invalid index type

### ISSUE THREAD

**Issue by EricSyu2816** [wuhuikai/FaceSwap#33]
There is a error occour when I execute the command
`python main.py --src imgs/test6.jpg --dst imgs/test7.jpg --out results/output6_7.jpg --correct_color`

How can I fix it? thanks!

**Comment by EricSyu2816** [comment]
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    src_points, src_shape, src_face = select_face(src_img)
  File "D:\Deep fake\FaceSwap\face_detection.py", line 37, in select_face
    bbox = faces[idx]
TypeError: Invalid index type

**Comment by kehlerr** [comment]
Probably there are no recognizible faces on photo

**Comment by wuhuikai** [comment]
> Probably there are no recognizible faces on photo

I think so~

**Comment by tisbuet** [comment]
Use **list(faces)[idx]** instead of faces[idx]

**Comment by 2007anu** [comment]
@kehlerr @tisbuet Index type error is still coming while executing below command:

python main.py --src imgs/test6.jpg --dst imgs/test7.jpg --out results/output6_7_2d.jpg --correct_color --warp_2d

Error:

TypeError                                 Traceback (most recent call last)
~\Downloads\FaceSwap\main.py in <module>()
     23 
     24     # Select src face
---> 25     src_points, src_shape, src_face = select_face(src_img)
     26     # Select dst face
     27     dst_faceBoxes = select_all_faces(dst_img)

~\Downloads\FaceSwap\face_detection.py in select_face(im, r, choose)
     35 
     36     if len(faces) == 1 or not choose:
---> 37         idx = np.argmax([(face.right() - face.left()) * (face.bottom() - face.top()) for face in faces])
     38         #print(idx)
     39         bbox = list(faces)[idx]

TypeError: Invalid index type

**Comment by 2007anu** [comment]
@kehlerr @tisbuet
