### ISSUE TITLE
IndexError: index 185 is out of bounds for axis 0 with size 185

### ISSUE THREAD

**Issue by IpsumDominum** [wuhuikai/FaceSwap#36]
Happens when detected face is out of bounds of the image.
Also, error in main_video.py line 55: 
```python3
if not os.path.isdir(dir_path):
        os.makedirs(dir_path)
```
Will output error if dir_path is ""

Edit:
```python3
if dir_path != "" and not os.path.isdir(dir_path):
        os.makedirs(dir_path)
```

**Comment by wuhuikai** [comment]
1. "detected face is out of bounds of the image" is a known issue, but I do not have time to fix this currently.
2. use "./" instead.
