### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by cshexin** [wuhuikai/FaceSwap#47]
Here are the error messages when I was running the main.py in Linux 

$ python3 main.py --src B.jpg --dst A.png --out result.jpg --correct_color

Traceback (most recent call last):
  File "/home/hexinhu/FaceSwap/main.py", line 41, in <module>
    os.makedirs(dir_path)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by wuhuikai** [comment]
try `python3 main.py --src ./B.jpg --dst ./A.png --out ./result.jpg --correct_color`
