### ISSUE TITLE
out of bounds

### ISSUE THREAD

**Issue by dczz** [wuhuikai/FaceSwap#5]
[root@vpc175 FaceSwap]# python main.py --src ./psb.jpg --dst ./sddefault.jpg --out ./out111.jpg   ##--correct_color
Traceback (most recent call  #last):
  File "main.py", line 81, in <module>
    warped_src_face = warp_image_3d(src_face, src_points[:48], dst_points[:48], (w, h))
  File "/opt/faceSwap/FaceSwap/face_swap.py", line 88, in warp_image_3d
    process_warp(src_img, result_img, tri_affines, dst_points, delaunay)
  File "/opt/faceSwap/FaceSwap/face_swap.py", line 60, in process_warp
    result_img[y, x] = bilinear_interpolate(src_img, out_coords)
IndexError: index 223 is out of bounds for axis 1 with size 223

**Comment by wuhuikai** [comment]
The possible reason is that the bbox of the face is near the boundary. You'd better enlarge the whole image. Or change `result_img[y, x] = bilinear_interpolate(src_img, out_coords)` to `result_img[y, x] = bilinear_interpolate(src_img, out_coords-1)`

**Comment by gabriben** [comment]
that didn't work out for me. I also tried `out_coords-20`. It does look like it is that kind of problem because I am trying to use your package on pre-cropped face images. Thx

**Comment by wuhuikai** [comment]
Can you show me the detail?

**Comment by gabriben** [comment]
I ended up forking your repo to allow for multiple swaps on the destination image.
See this pull request: https://github.com/wuhuikai/FaceSwap/pull/35
I hope this is useful.

Thanks a lot for this repo, I had an intro to Python workshop yesterday with non-coder colleagues and they had fun faceswapping their faces on other people's.

**Comment by wuhuikai** [comment]
Glad to see it, and thanks for your contribution.
