### ISSUE TITLE
Swap only part of face?

### ISSUE THREAD

**Issue by wanshun123** [wuhuikai/FaceSwap#6]
Is it possible to swap only part of the face (eg. mouth and nose region)?

**Comment by wuhuikai** [comment]
Yes. The original algorithm returns 68 points as shown in this [line](https://github.com/wuhuikai/FaceSwap/blob/ccb8ef4022a1f00944aefddd510b486273f92237/face_points_detection.py#L20). Modifying the returned points can control the part of the face you want to swap.
