### ISSUE TITLE
Seamless face swap on video

### ISSUE THREAD

**Issue by wanshun123** [wuhuikai/FaceSwap#8]
First off thanks for developing this as it works very well. I've been experimenting with face swapping on video (by running main.py on the n-th source video frame with the n-th destination video frame for all frames, where both videos have the same framerate) and am finding there is a flickering between frames due to the head positions being different. Here is an example result:

https://www.youtube.com/watch?v=YrNXIyn1Pgo

(Source video at https://www.youtube.com/watch?v=hxBgVnEjdVw and destination video at https://www.youtube.com/watch?v=Ob9ExceBitc)

Is it feasible to have this work for video where there is no flickering as in the result above?

**Comment by wuhuikai** [comment]
It's difficult to reduce flickering with minor modification. But first, you can try to remove all the blending operations and just use 2d/3d warp.

**Comment by xiangshaocheng** [comment]
I guess it is dlib's fault. cause dlib sometimes gets the landmarks of face not as accurate as expected

**Comment by wuhuikai** [comment]
If dlib is the problem, you can replace it with OpenCV or other face detectors. PR is welcome :)

**Comment by ghost** [comment]
@wuhuikai any update on this issue, I am also getting flickering in video after combined frames

**Comment by wuhuikai** [comment]
It's mainly for face swap in images. There's no plan to solve the problem in videos.

**Comment by ghost** [comment]
@wuhuikai when you say "remove all the blending operations and just use 2d/3d warp."  Do you mean take out the --correct_color option and keep --warp_2d?

**Comment by wuhuikai** [comment]
Yes, and maybe try [this script](https://github.com/wuhuikai/FaceSwap#video) developed for video.
